name: barys_biotracker
description: "КАЛКАН СПОРТ · СААТ-1 - Кроссплатформенное приложение биометрического мониторинга с персонажем «Барыс-Батыр»"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.11.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  shared_preferences: ^2.5.5
  firebase_core: ^4.15.0
  firebase_auth: ^6.7.0
  image_picker: ^1.2.3
  home_widget: ^0.10.0
  path_provider: ^2.1.5
  share_plus: ^13.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Manrope
      fonts:
        - asset: assets/fonts/Manrope-Regular.ttf
          weight: 400
        - asset: assets/fonts/Manrope-Regular.ttf
          weight: 500
        - asset: assets/fonts/Manrope-Regular.ttf
          weight: 600
    - family: IBM Plex Mono
      fonts:
        - asset: assets/fonts/IBMPlexMono-Regular.ttf
          weight: 400
        - asset: assets/fonts/IBMPlexMono-Medium.ttf
          weight: 500
        - asset: assets/fonts/IBMPlexMono-SemiBold.ttf
          weight: 600
