name: barys_biotracker
description: "КАЛКАН СПОРТ · СААТ-1 - Кроссплатформенное приложение биометрического мониторинга с персонажем «Барыс-Батыр»"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.11.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  shared_preferences: ^2.5.5
  firebase_core: ^4.15.0
  firebase_auth: ^6.7.0
  image_picker: ^1.2.3
  home_widget: ^0.10.0
  path_provider: ^2.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
